version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    assignees:
      - "jingairpi"
    reviewers:
      - "jingairpi"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "npm"
    assignees:
      - "jingairpi"
    reviewers:
      - "jingairpi"
