name: Release CI

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set release branch name
        id: set_release_branch
        run: |
          TAG_NAME=$(date +"%m%d%y-%H%M")
          echo "RELEASE_BRANCH=release-${TAG_NAME}" >> $GITHUB_ENV

      - name: Ensure release branch exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin
          if git show-ref --quiet refs/heads/${{ env.RELEASE_BRANCH }}; then
            echo "Release branch exists"
            git checkout ${{ env.RELEASE_BRANCH }}
          else
            echo "Creating release branch"
            git checkout -b ${{ env.RELEASE_BRANCH }}
            git push origin ${{ env.RELEASE_BRANCH }}
          fi

      - name: Merge main into release
        run: |
          git checkout ${{ env.RELEASE_BRANCH }}
          git merge origin/main --no-edit

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build the action
        run: npm run build

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f dist/ action.yml
          git commit -m "Build for release ${GITHUB_REF_NAME}" || echo "No changes to commit"

      - name: Push changes to release branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://$GITHUB_ACTOR:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push origin ${{ env.RELEASE_BRANCH }}

      - name: Create or update tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag -fa ${GITHUB_REF_NAME} -m "Release ${GITHUB_REF_NAME}"
          git push origin ${GITHUB_REF_NAME} --force

      - name: Create GitHub Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          files: |
            dist/**
            action.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
