name: Release CI

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set release branch name
        id: set_release_branch
        run: |
          DATE=$(date +"%Y-%m-%d")
          echo "RELEASE_BRANCH=release-${DATE}" >> $GITHUB_ENV

      - name: Ensure release branch exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch all branches
          git fetch origin
          # Check if release branch exists
          if git show-ref --quiet refs/heads/${{ env.RELEASE_BRANCH }}; then
            echo "Release branch exists"
            git checkout ${{ env.RELEASE_BRANCH }}
          else
            echo "Creating release branch"
            git checkout -b ${{ env.RELEASE_BRANCH }}
            git push origin ${{ env.RELEASE_BRANCH }}
          fi

      - name: Merge main into release
        run: |
          git checkout ${{ env.RELEASE_BRANCH }}
          git merge origin/main --no-edit

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build the action
        run: npm run build

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f dist/ action.yml
          git commit -m "Build for release ${GITHUB_REF_NAME}" || echo "No changes to commit"

      - name: Push changes to release branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Set up authentication
          git remote set-url origin https://$GITHUB_ACTOR:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push origin ${{ env.RELEASE_BRANCH }}

      - name: Create or update tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag -fa ${GITHUB_REF_NAME} -m "Release ${GITHUB_REF_NAME}"
          git push origin ${GITHUB_REF_NAME}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          fail_if_exists: false
