name: Test Action
permissions:
  contents: read
  pull-requests: write

on: [push]

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run hello-world action
        uses: jingairpi/hello-world-action@05358dc1002895a3ffb4db44d44b16af444bb74f # v1.11
